(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(blink-cursor-mode nil)
 '(blink-matching-paren t)
 '(coffee-tab-width 2)
 '(column-number-mode t)
 '(company-idle-delay 0.2)
 '(custom-safe-themes
   (quote
    ("8db4b03b9ae654d4a57804286eb3e332725c84d7cdab38463cb6b97d5762ad26" "4aee8551b53a43a883cb0b7f3255d6859d766b6c5e14bcb01bed572fcbef4328" default)))
 '(electric-pair-mode nil)
 '(elscreen-tab-display-control nil t)
 '(emojify-display-style (quote unicode) t)
 '(evil-toggle-key "C-z")
 '(exec-path-from-shell-arguments (quote ("-l")))
 '(flycheck-indication-mode nil)
 '(flycheck-ruby-executable "/usr/local/var/rbenv/shims/ruby")
 '(flycheck-ruby-rubocop-executable "/usr/local/var/rbenv/shims/rubocop")
 '(global-emojify-mode t t)
 '(helm-gtags-highlight-candidate t)
 '(helm-gtags-use-input-at-cursor t)
 '(ido-enable-flex-matching t)
 '(js-indent-level 2)
 '(js2-basic-offset 2)
 '(js2-bounce-indent-p t)
 '(js2-indent-switch-body t)
 '(js2-mode-show-parse-errors nil)
 '(js2-mode-show-strict-warnings nil)
 '(jscs-command "jscs")
 '(json-reformat:indent-width 2)
 '(less-css-compile-at-save t)
 '(linum-relative-current-symbol "" t)
 '(magit-push-always-verify nil t)
 '(org-agenda-files (quote ("~/Dropbox/org/gtd.org")))
 '(org-bullets-bullet-list (quote ("•" "†" "‡")))
 '(org-hide-leading-stars t)
 '(org-indent-mode-turns-off-org-adapt-indentation nil)
 '(ruby-deep-arglist nil)
 '(send-mail-function (quote smtpmail-send-it))
 '(show-paren-mode t)
 '(show-paren-style (quote mixed))
 '(sml/mode-width (quote right))
 '(sml/name-width 44)
 '(sml/vc-mode-show-backend nil)
 '(smtpmail-smtp-server "mail.messagingengine.com")
 '(smtpmail-smtp-service 587)
 '(tool-bar-mode nil)
 '(typescript-indent-level 2)
 '(visual-line-fringe-indicators (quote (left-curly-arrow right-curly-arrow)))
 '(web-mode-code-indent-offset 2)
 '(web-mode-css-indent-offset 2)
 '(web-mode-markup-indent-offset 2))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(sml/git ((t (:foreground "#005c4d" :slant italic))))
 '(sml/minor-modes ((t (:inherit sml/global :slant italic))))
 '(sml/position-percentage ((t (:inherit sml/prefix :slant italic :weight normal))))
 '(sml/projectile ((t (:foreground "#23249e"))))
 '(sml/vc-edited ((t (:foreground "#da0039" :slant italic :weight normal))))
 '(term ((t (:inherit default :background "#f1f2f1" :foreground "#212822"))))
 '(term-color-black ((t (:foreground "#616568"))))
 '(term-color-blue ((t (:foreground "#23249e"))))
 '(term-color-cyan ((t (:foreground "#23249e"))))
 '(term-color-green ((t (:foreground "#005c4d"))))
 '(term-color-magenta ((t (:foreground "#600b92"))))
 '(term-color-red ((t (:foreground "#600b92"))))
 '(term-color-white ((t (:foreground "#616568"))))
 '(term-color-yellow ((t (:foreground "#785a20"))))
 '(term-default-bg-color "#211E1E")
 '(term-default-fg-color "#AAAAAA")
 '(variable-pitch ((t (:height 1.2)))))
