All my Dotfiles managed with [[https://www.gnu.org/software/stow/][GNU Stow]]

Includes config files for:
 - Emacs
 - Vim
 - Fish
 - Xmonad
 - Xmobar
 - bash
 - git
 - st
 - dmenu

* Usage

  There are two parts to my dotfiles:

  1. Install scripts: they help me to install softwares on my
  different computers. Those are named /install_computer_type.sh/.
  On a fresh install I use them but they also serve as documentation
  when I switch between computers. It makes it easier to remember
  which software I need.
  2. All the directories are meant to be used with stow. I split my
     config files depending on usage and importance of the software.
     For example Emacs as a dedicated folder even though It could have
     been included inside the ~home~ directory.

  Example Usage:

  - run ~install_linux.sh~
  - run ~stow <directory-name>~ commands to symlink directories
    For example on my linux desktop machine I run:
    ~stow home~
    ~stow home_linux~
    ~stow_home_linux_desktop~

* bin

  The bin directory contains scripts that I use from time to time.

  There are scripts to
  - get the local time in San Francisco
  - launch tmux sessions /tat/
  - test colors in the terminal /colortest/
  - get the dropbox status /dropboxStatus/
  - change the brigthness on my laptop /brightness/.
