#!/bin/bash
# run with $ sudo stow -t / root
# this is to fix the non working keyboard and touchpad on my infinity book pro after sleep

case $1 in
    pre)
      modprobe -R i8042
    ;;
    post)
      modprobe i8042
      setxkbmap -option "ctrl:nocaps"
    ;;
esac
