#!/bin/sh

if eval "git diff --cached | grep 'binding.pry'"; then
    echo "You have a binding.pry somewhere"
    exit 1
fi

if eval "git diff --cached | grep 'debugger'"; then
    echo "You have a debugger somewhere"
    exit 1
fi

echo "\033[0;32m  Well done young Padawan. Your code seems light enough.\033[0m"
